### ISSUE TITLE
RetroPie licence violation

### ISSUE THREAD

**Issue by joolswills** [harryzimm/RetrOrangePi#3]
I understand you are annoyed at the RetroEngine Sigma utilising "your code", but you are getting confused about how licences work.

What you think of as "your work" is in fact fork of RetroPie-etup (and of course retropie as a whole builds on top of many other projects like RetroArch, Emulation Station and so on). You need to respect the RetroPie licence if you are using our code. Pulling your fork of our code is in breach of the RetroPie GPL licence. I also see you are still providing binary downloads from your site.

I'm very disappointed at this. I also suspect even with the RetroPie repository in place you are in breach of other software licences, as the code I last saw in your repo last, didn't seem to reflect all the changes.

Please respect the licences of the projects your are using.

tagging @HerbFargus @PetrockBlog

**Comment by harryzimm** [comment]
I apologise about this. When we say "our work" we are not referring to you guys or any of the other code we use. We are the first to credit retropie and the work of the other projects included. 

We are currently switching to another github account https://github.com/retr0rangepi

We will update this with all current work over the next weeks.  This is still all quite new to us and we will do our most to comply with the GPL.

**Comment by harryzimm** [comment]
Our github has now moved to https://github.com/retr0rangepi
